### ISSUE TITLE
Feature: Annotations, TOC and Search

### ISSUE THREAD

**Issue by viezel** [barteksc/PdfiumAndroid#1]
Hi there,
I worked on the PDFium for a year ago to create support for some of the basic features in a PDF viewer. I wonder if you plan to incorporate features link Annotation links, Table of Content and Search? 

Ive added support for the text module, as you can see here: https://github.com/viezel/PdfiumAndroid/blob/78f7f67cbb4dcfdcda6f2885aeae168f8ea11c9d/src/main/jni/src/mainJNILib.cpp#L263-L389 

Would that have your interest?

**Comment by viezel** [comment]
An interesting C# implementation of all the features of PDFium lib for inspiration:
https://github.com/pvginkel/PdfiumViewer/blob/master/PdfiumViewer/NativeMethods.Pdfium.cs

**Comment by barteksc** [comment]
Hi, I have plans to incorporate such features, but it will take me some time. Thank you for referencing your source, it'll be very useful. Unfortunately implementing these features in AndroidPdfViewer may consume much more time.

**Comment by viezel** [comment]
Cool. You have any timeline for these features? 
I would gladly test out the work. :)

**Comment by viezel** [comment]
I'm not much of a c++ developer, but can help out with the interface in java

**Comment by barteksc** [comment]
Unfortunately there is not any timeline, I work on this library when I have some free time.
Version 1.2.0 introduced support for reading documents' metadata and Table Of Contents

**Comment by viezel** [comment]
Very cool progress :+1:

**Comment by ncruces** [comment]
Any progress on this? It'd be quite useful to me if PdfiumAndroid implemented something like this (even if it doesn't get used by AndroidPdfViewer).

I'm not sure how much help I could be (using your library from gradle, I've yet to try to build it, not sure if viable on Windows), but I'll do my best if there's a decent chance of getting something merged.
