### ISSUE TITLE
Method for reproducibly rebuilding the bundled pdfium shared objects?

### ISSUE THREAD

**Issue by orospakr** [barteksc/PdfiumAndroid#10]
I filed this upstream, figuring that only the original author knew how he built the shared objects checked into git, but I see that @barteksc rebuilt them after all according to git history.  Sorry for the issue duplication, but it appears that upstream has gone silent anyhow.

Repost:

> It would be awesome if the project had documentation for building the shared objects again from source, and where the source code that produced them lives, and also what specific version built them in order to reproduce them deterministically. Right now all we have is ELF blobs checked into git.
> 
> Was it the upstream android pdfium tree (https://android.googlesource.com/platform/external/pdfium/) that built them? If so, is it possible to document how it was done (scripting it would be even better) so it can be readily reproduced for new versions of pdfium?
> 
> Thank you!

https://github.com/mshockwave/PdfiumAndroid/issues/12

**Comment by barteksc** [comment]
Source and instructions are available on my github: https://github.com/barteksc/modpdfium

**Comment by orospakr** [comment]
Awesome, thank you!

**Comment by KnIfER** [comment]
https://github.com/KnIfER/PDFium-Android-Demo demostrates a cheaper way of compiling libpdfium.so

[precompiled_libpdfium_aarch64.zip](https://github.com/barteksc/PdfiumAndroid/files/5428028/precompiled_libpdfium_aarch64.zip)
