### ISSUE TITLE
Signature field flattening is not working

### ISSUE THREAD

**Issue by matpag** [barteksc/PdfiumAndroid#20]
I'm using this code in my app to flatten a PDF with signatures added.

    PdfiumCore pdfiumCore = new PdfiumCore(context);
    ParcelFileDescriptor pfd = ParcelFileDescriptor.open(myFile, ParcelFileDescriptor.MODE_READ_ONLY);
    PdfDocument pdfDocument = pdfiumCore.newDocument(pfd);

    pdfiumCore.openPage(pdfDocument, page);

    int width = pdfiumCore.getPageWidthPoint(pdfDocument, page);
    int height = pdfiumCore.getPageHeightPoint(pdfDocument, page);

    Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
    pdfiumCore.renderPageBitmap(pdfDocument, bitmap, page, 0, 0, width, height);

But the resulting image created from the `bitmap` object won't have the signature fields drawn. Can i do something to add those signature fields to the flattening process?

Thanks
Mat

**Comment by barteksc** [comment]
Creating bitmap doesn't flatten pdf document. There is method for flattening in Pdfium, but it's not exposed in Java.

**Comment by matpag** [comment]
I thought `renderPageBitmap` performed flattening + converion to Bitmap all togheter.

What is the corresponding C++ method in the library to do this? (i don't know too much about C++ but if it's not too hard i can try to create a PR with a wrapper function for this feature)

**Comment by matpag** [comment]
I've performed some researches and work, i've created a new method and in the last part of it (following the renderPageBitmap code) I've added the central lines.

    ....
    FPDFBitmap_FillRect( pdfBitmap, baseX, baseY, baseHorSize, baseVerSize,
                         0xFFFFFFFF); //White

    //flat the PDF before proceeding with Bitmap creation
    const int result = FPDFPage_Flatten(page, flatType);
    if (result == FLATTEN_FAIL){
        jniThrowException(env, "com/shockwave/pdfium/PdfiumCore", "PDF flattening has failed.");
    }

    FPDF_RenderPageBitmap( pdfBitmap, page,
                           startX, startY,
                           (int)drawSizeHor, (int)drawSizeVer,
                           0, flags );
    .....

i've tried with 2 different sample PDF with form fields filled, but a the end i only get a PDF without them.
Maybe i need to save and reopen the document?
Any suggestions?

**Comment by barteksc** [comment]
Sorry, I forgot to mention that you should try using last parameter of `.renderPage()` method, which is `boolean renderAnnot`. It should render annotations and forms.

**Comment by matpag** [comment]
Lol. it's working passing true to the `renderAnnot` param.
I've wasted an evening working on something which was already working XD (at least i've learned something new 😋)
Btw thank you man, i've created a PR to updated the example code to avoid future issues on the same thing

**Comment by barteksc** [comment]
Sorry not mentioning it immediately. Thanks for update, I will pull it.
