### ISSUE TITLE
dlopen failed in Android 5.1 

### ISSUE THREAD

**Issue by allenzhangp** [barteksc/PdfiumAndroid#22]
art	dlopen("/data/data/xxx/app_libs/arm64-v8a/libmodft2.so", RTLD_LAZY) failed: dlopen failed: library "libmodpng.so" not found
java.lang.UnsatisfiedLinkError: dlopen failed: library "libmodpng.so" not found
	at java.lang.Runtime.load(Runtime.java:332)
	at java.lang.System.load(System.java:981)
	at com.shockwave.pdfium.PdfiumCore.loadLibrary(PdfiumCore.java:45)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Error	20:51:46.017	828	10302	GED	Failed to get GED Log Buf, err(0)

**Comment by barteksc** [comment]
How do you include library?

**Comment by allenzhangp** [comment]
System.load("/data/data/XXXX/files/libmodpng.so");

**Comment by barteksc** [comment]
How do you include PdiumAndroid. Or do you manually load native libs?

**Comment by allenzhangp** [comment]
Yes，I was download so file to /data/data/XXXX/app_libs/，and manually load native libs

**Comment by allenzhangp** [comment]
https://stackoverflow.com/questions/31978714/android-5-1-load-64-bits-shared-library-failed-due-to-its-depend-library-not-fou

**Comment by barteksc** [comment]
I am distributing native libraries as a part of whole PdfiumAndroid library and I am sure that it works. If you are extracting part of it, I cannot help

**Comment by ashtrisk** [comment]
Hey guys, I am getting the same issue. I have built one module of opencv into .so file myself. I am trying to load this in my project, but getting this same error : UnsatisfiedLinkError : dlopen failed. This issue looks to be closed. Did anyone find any solutions which can help me?
