### ISSUE TITLE
Is there a method for getting thumb bitmaps from pdf once?

### ISSUE THREAD

**Issue by donal-tong** [barteksc/PdfiumAndroid#23]
I have display page bitmap in list, so I have to render the page like this, but have a problem that not scroll smooth
![image](https://user-images.githubusercontent.com/2238211/27365761-639ea4be-5674-11e7-959a-1ee4849f41b2.png)

**Comment by barteksc** [comment]
You should cache generated bitmaps. I don't see any usage of PdfiumAndroid in attached code

**Comment by barteksc** [comment]
Closing due to no response from author

**Comment by donal-tong** [comment]
I already cached the bitmaps, but now while rendering bitmaps telling do much work in main thread, how fix?
