### ISSUE TITLE
Signature not rendered on pdf

### ISSUE THREAD

**Issue by AlbertoZanatta** [barteksc/PdfiumAndroid#24]
I am currently using this library in order to render the pages of my pdf documents - it's very fast and efficient.
However, visible signatures are not rendered and therefore they are not visible on the bitmap that shows the content of a pdf page. 
This is the code I use to render the pdf pages into bitmaps:

         File pdfFile = new File(pdfPath);
         ParcelFileDescriptor fileDescriptor = ParcelFileDescriptor.open(pdfFile, ParcelFileDescriptor.MODE_READ_ONLY);
          PdfiumCore pdfiumCore = new PdfiumCore(this);
          PdfDocument pdfDocument = pdfiumCore.newDocument(fileDescriptor); 
          List<Bitmap> previewList = = new ArrayList<Bitmap>();
          for(int pageNum=0; pageNum < pdfiumCore.getPageCount(pdfDocument); pageNum++){
          pdfiumCore.openPage(pdfDocument, pageNum);
          int width = pdfiumCore.getPageWidthPoint(pdfDocument, pageNum);
          int height = pdfiumCore.getPageHeightPoint(pdfDocument, pageNum);

          Bitmap bitmap = Bitmap.createBitmap(width*2, height*2, Bitmap.Config.ARGB_8888);
          pdfiumCore.renderPageBitmap(pdfDocument, bitmap, pageNum, 0, 0, width*2, height*2);

          previewList.add(bitmap);
        }
(then i set the first bitmap as the background image of a custom ImageView)

This is an example of pdf document whose signature is not correctly rendered:
[pdf-test[1].pdf](https://github.com/barteksc/PdfiumAndroid/files/1108656/pdf-test.1.pdf)

Is there a way to overcome this issue?
Thanks for your time and patience,
Alberto

**Comment by barteksc** [comment]
You may try rendering annotations adding `true` as last parameter of `renderPageBitmap` method. If it doesn't work, I'm afraid there is no other solution.

**Comment by AlbertoZanatta** [comment]
Thanks! It works perfectly!
