### ISSUE TITLE
How can i fill forms using this library ?

### ISSUE THREAD

**Issue by nuwanchamara** [barteksc/PdfiumAndroid#29]
I want to froms in PDF  (fallible PDFs) i it possible with this library?

**Comment by barteksc** [comment]
Unfortunately there is no such possibility

**Comment by nuwanchamara** [comment]
is it possible with this https://github.com/barteksc/AndroidPdfViewer ?

**Comment by barteksc** [comment]
It is based on PdfiumAndroid, so no, it is not possible.
