### ISSUE TITLE
C++ Library Support

### ISSUE THREAD

**Issue by ncruces** [barteksc/PdfiumAndroid#37]
Have you had a chance to look into [this](https://github.com/barteksc/AndroidPdfViewer/issues/439)?

You're using `gnustl_static` as your STL. According to [this](https://developer.android.com/ndk/guides/cpp-support.html#static_runtimes), that means users of PdfiumAndroid (including AndroidPdfViewer) can't use C++ *anywhere else* in their projects. I have to do just that.

If I were to build a version around `c++_shared` (which seems the preferred version these days), would this be something you'd merge?

**Comment by barteksc** [comment]
Sorry for not responding for long time.
If you can build version with c++_shared support - please do it and I will pull your changes into this repository

**Comment by ncruces** [comment]
I've made the changes to [modpdfium](https://github.com/barteksc/modpdfium), and pushed some binaries.

I'm using a [JNA](https://github.com/java-native-access/jna) wrapper, so I haven't tried building PdfiumAndroid.

But I'm pretty sure the only changes you'd need are:
- change `gnustl_static` for `c++_shared` [here](https://github.com/barteksc/PdfiumAndroid/blob/master/src/main/jni/Application.mk#L1)
- use libs from [here](https://github.com/ncruces/modpdfium/releases/tag/android-7.1.2_r36)

**Comment by ncruces** [comment]
I've just noted barteksc/AndroidPdfViewer#253.

Is [this](https://issuetracker.google.com/issues/37131979#comment16) the fix you've applied to build [these](https://github.com/barteksc/PdfiumAndroid/commit/c873b24)?

**Comment by ncruces** [comment]
Binaries posted [here](https://github.com/ncruces/modpdfium/releases/tag/android-7.1.2_r36) already include the fix for barteksc/AndroidPdfViewer#253.

**Comment by barteksc** [comment]
Thank you, resolved in 1.9.0
