### ISSUE TITLE
mips64

### ISSUE THREAD

**Issue by axet** [barteksc/PdfiumAndroid#39]
maven uploades does not contain mips64 libraries. Not like we need it, or here is a mips devices at all :)

But since you have mips32 builded, and google recently announed all apps should have 64 bit support added to all arch's, why not to add one more mips64 to to build config?

**Comment by ncruces** [comment]
`armeabi`, `mips` and `mips64` have all been deprecated in NDK r16 and removed in r17
https://developer.android.com/ndk/guides/abis

They're not impossible to build, but significantly harder (if you're using r17).
