### ISSUE TITLE
a visit

### ISSUE THREAD

**Issue by jumpsH** [barteksc/PdfiumAndroid#4]
i used android-pdf-view and build my apk,then size +16MB,then i traced to this project,
 too big!  i can't refactor this project.
give me a way, please.please!please;

**Comment by barteksc** [comment]
Just read the README

**Comment by jumpsH** [comment]
ok ok I gave up, i try another way:
build.gradle->defaultConfig-> ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
size -8MB   done! haha

**Comment by jumpsH** [comment]
ok ok I gave up, i try another way:
build.gradle->defaultConfig-> ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
size -8MB   done! haha

**Comment by jumpsH** [comment]
ok ok I gave up, i try another way:
build.gradle->defaultConfig-> ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
size -8MB   done! haha

**Comment by jumpsH** [comment]
ok ok I gave up, i try another way:
build.gradle->defaultConfig-> ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
        }
size -8MB   done! haha
