### ISSUE TITLE
original cpp source code

### ISSUE THREAD

**Issue by axet** [barteksc/PdfiumAndroid#41]
Hello!

Where can I found source code for the binary files you attached in the repo? I want to recompile it and see source (commit revs) for for three libraries: libmodpdfium.so, libmodft2.so, libmodpng.so

Or you do not have source, except link you provided?

**Comment by MasterEmit** [comment]
You may want to take a look at this: https://github.com/barteksc/modpdfium

I'm currently trying to update these libs to get the latest bugfixes. Sadly it seems to me that just replacinng make files will not work anymore.

**Comment by axet** [comment]
You can use my already:

  * https://gitlab.com/axet/android-pdfium

**Comment by MasterEmit** [comment]
Ah great! You found some additional information I missed. At the end we need to be able to build everything by ourself - but with your additional links this should be possible now.
