### ISSUE TITLE
Support Android Gradle plugin 3.+

### ISSUE THREAD

**Issue by ToxicBakery** [barteksc/PdfiumAndroid#44]
With the release of the Android Gradle 3 plugin and Android Studio 3 we can leverage the new build tools as well as built in C/C++ support in the editor. I did the leg work on this in a branch so I could test my own custom built versions of the libpdfium.so

Pros
* With the NDK and Cmake installed from the Sdk Manager, the JNI and thus the AAR can be built without needing the extra manual ndk-build step.
* Switching to Cmake allows the build tools to build the JNI multiple times for multiple platform levels automagically (or that's how I understand it)
* All the free IDE features work properly now

Cons
* Requires switching to API 14 minimum, however, API 9 is basically dead anyways

Would you be interested in merging this? If so I can open a PR for it.

Ref: https://github.com/ToxicBakery/PdfiumAndroid/tree/feature/test-custom-pdfium

**Comment by barteksc** [comment]
Resolved in 1.9.0
