### ISSUE TITLE
Update of support library

### ISSUE THREAD

**Issue by mcBIG** [barteksc/PdfiumAndroid#51]
Hi, did you consider to update support library dependency in your project? I get that due to this action this library will have support only for apps with min sdk 14, but nowadays this is enough. 

Also on this years Google IO, Google announced that apps has to target at least sdk 26, and it is good practice to keep support libraries at the same version as compileSdk. 

Now i have to keep support library version in my app on version 25.3.1 the same as yours, because all  support libraries has to have exact same version.

**Comment by barteksc** [comment]
Resolved in 1.9.0
