### ISSUE TITLE
Apk size increased upto 15 MB

### ISSUE THREAD

**Issue by shanraisshan** [barteksc/PdfiumAndroid#6]
Including the dependency
````java
compile 'com.github.barteksc:pdfium-android:1.4.0'
````
increasing the apk size upto **15.4 MB**,

----
I just want to use this library for creating thumb from a pdf page.

***Q.* Is there any way to just include a specific module from this library that is used to perform only Pdf page rendering?**

like google library, you just need to add specific modules, not whole library
for example, for map
````java
compile 'com.google.android.gms:play-services-maps:8.4.0'
````

**Comment by barteksc** [comment]
This library does not have any modules, it is used only for pages rendering.
To solve your problem read this section: https://github.com/barteksc/AndroidPdfViewer/#why-resulting-apk-is-so-big

**Comment by shanraisshan** [comment]
Not so cool :-1:, I wonder what is WhatsApp using, as there is no increased in Apk size, after they added the document sharing feature.

Thanks for help btw :+1:
