### ISSUE TITLE
Is the lib free to use ?

### ISSUE THREAD

**Issue by himanshusinghs** [barteksc/PdfiumAndroid#68]
I can see that it is built upon [Google AOSP Pdfium](https://android.googlesource.com/platform/external/pdfium/) but nowhere did I find license related information.

Our application will use this library to generate thumbnails for pdfs and itself will be available for free download on Google Play store (basic version).

**Comment by XCarbone** [comment]
how to you generate thumbnails with this lib ? I want to do it but no idea how
