### ISSUE TITLE
Save loaded Pdf to another location (Isuue due to Google Drive Files)

### ISSUE THREAD

**Issue by isolpak1** [barteksc/PdfiumAndroid#7]
I am using 
````java
ParcelFileDescriptor fd = App.applicationContext.getContentResolver().openFileDescriptor(pdfUri, "r");
PdfDocument pdfDocument = pdfiumCore.newDocument(fd);
````
to load Pdf document.

Is there any way to save this document to any other location using Pdfium Android?

Basically I am getting uri from Google drive file, I want to save that file in my local storage.

**Comment by barteksc** [comment]
This library does not copy or save files, use Android API for such cases.
