### ISSUE TITLE
How to check if a pdf file is password protected

### ISSUE THREAD

**Issue by NayabSarfraz** [barteksc/PdfiumAndroid#75]
Hi i am using **_com.github.barteksc:pdfium-android:1.9.0_** to view pdf files in my app. I want to handle encrypted files. On opening an encrypted file without providing a password triggers the onErrorListener which has throwable. I want to show a password dialog in this case. Is there any way to check if the file is password protected so that i can show dialog in this case or is there any way to determine whether the exception is an exception because of password?

**Comment by AhmerAfzal1** [comment]
```
.onError(t -> {
    if (t instanceof PdfPasswordException) {
    showPasswordDialog();
    }
})
```

**Comment by NayabSarfraz** [comment]
> ```
> .onError(t -> {
>     if (t instanceof PdfPasswordException) {
>     showPasswordDialog();
>     }
> })
> ```

Thanks

**Comment by NayabSarfraz** [comment]
> ```
> .onError(t -> {
>     if (t instanceof PdfPasswordException) {
>     showPasswordDialog();
>     }
> })
> ```

How to handle this in case of pro-guard on?

**Comment by AhmerAfzal1** [comment]
More about [pro-guard](https://github.com/barteksc/AndroidPdfViewer#proguard)
`-keep class com.shockwave.**`

**Comment by AhmerAfzal1** [comment]
This is also good
```
-keep class com.github.barteksc.pdfviewer.**{*;}
-keep class com.shockwave.pdfium.**{*;}
```

**Comment by NayabSarfraz** [comment]
It worked. Closing
